### ISSUE TITLE
[FEAT] Persistence Layer 구성 추가

### ISSUE THREAD

**Issue by 320Hwany** [U2DJ2/booki-today#10]
## ⚙️ 어떤 기능인가요?

> 요구 사항 변경에 따른 DB 엔티티 및 repository 수정 및 추가

## 🔎 작업 상세 내용

- [X] BaseTimeEntity 추가
- [X] 대학교 - University
- [X] 카테고리 - Category
- [X] 이메일 인증 번호 - EmailCertificationNumber
- [X] 회원 컬럼 수정 - Member

**Comment by Anak-2** [comment]
LGTM b
